TodolistProject.Core/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TodolistProject.Core.Models.RoleViewModels;
using TodolistProject.Core.Models.UserModels;
using TodolistProject.Service;

namespace TodolistProject.Core.Controllers
{
    [Authorize(Roles = "admin")]
    public class RoleController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<CommonUser> _userManager;

        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<CommonUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public async Task<IActionResult> ShowAllRoles()
        {
            ChangeRoleViewModel model = new ChangeRoleViewModel();
            model.AllUsers = _userManager.Users.ToList();
            model.UserRoles = new string[model.AllUsers.Count][];
            for (int i = 0; i < model.AllUsers.Count; i++)
            {
                var UserRole = await _userManager.GetRolesAsync(model.AllUsers[i]);
                model.UserRoles[i] = new string[UserRole.Count];
                for (int j = 0; j < UserRole.Count; j++)
                {
                    model.UserRoles[i][j] = UserRole[j];
                }
            }
         
            var roles = _roleManager.Roles.ToList();
            model.AllRoles = roles;
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteUser(string id)
        {
            var NewUser = await _userManager.FindByIdAsync(id);
            await _userManager.DeleteAsync(NewUser);
            UserService service = new UserService();
            service.DeleteUserData(id);
            
            return Json(id);
        }

        [HttpPost]
        public IActionResult BanUser(string id)
        {
            UserService service = new UserService();
            service.BanUser(id);
            return Json(id);
        }

        [HttpPost]
        public IActionResult UnbanUser(string id)
        {
            UserService service = new UserService();
            service.UnbanUser(id);
            return Json(id);
        }

        //чтобы добавить пользователя - убрать права сверху на роль и запустить
        public async Task<IActionResult> InitializeRoles()
        {
            string adminEmail = "rood@mail.ru";

            if (await _roleManager.FindByNameAsync("admin") == null)
            {
                await _roleManager.CreateAsync(new IdentityRole("admin"));
            }
            if (await _roleManager.FindByNameAsync("user") == null)
            {
                await _roleManager.CreateAsync(new IdentityRole("user"));
            }
            if (await _userManager.FindByEmailAsync(adminEmail) != null)
            {
                CommonUser admin = await _userManager.FindByNameAsync(adminEmail);
                var userRoles = await _userManager.GetRolesAsync(admin);
                await _userManager.AddToRoleAsync(admin, "admin");
                return Content("succeed");
            }
            else
                return Content("failure");

        }
    }
}

TodolistProject.Core/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TodolistProject.Core.Models.TaskViewModel;
using TodolistProject.Core.Models.UserModels;
using TodolistProject.Service;
using TodolistProject.Service.Dtos;

namespace TodolistProject.Core.Controllers
{
    [Authorize]
    public class TaskController : Controller
    {
        private readonly UserTaskService _service;
        private readonly UserManager<CommonUser> _userManager;

        public TaskController(UserManager<CommonUser> userManager)
        {
            _userManager = userManager;
            _service = new UserTaskService();
        }

        public IActionResult CreateTask()
        {
            TaskViewModel model = new TaskViewModel();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateTask([FromBody]TaskViewModel task)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user.IsBanned == true)
            {
                Response.Redirect("../Home/Bunned");
            }
            var userTaskDto = new UserTaskDto();
            userTaskDto.UserId = user.Id;
            userTaskDto.TaskDescription = task.TaskDescription;
            userTaskDto.TaskName = task.TaskName;
            userTaskDto.Priority = task.Priority;
            _service.AddTask(userTaskDto);
            return Ok(task);
        }

        public async Task<IActionResult> ShowAllTasks(string filter)
        {
            TasksViewModel AllTask = new TasksViewModel();
            var user = await _userManager.GetUserAsync(HttpContext.User);
            List<UserTaskDto> serviceAllTasks = _service.GetAllTasks(user.Id);
            List<TaskViewModel> models = new List<TaskViewModel>();
            foreach (var task in serviceAllTasks)
            {
                if (filter == null || task.Priority == filter || filter == "All")
                {
                    TaskViewModel model = new TaskViewModel();
                    model.Id = task.Id;
                    model.TaskName = task.TaskName;
                    model.TaskDescription = task.TaskDescription;
                    model.Priority = task.Priority;
                    model.Status = task.Status;
                    models.Add(model);
                }
            }
            AllTask.Tasks = models;
            return View(AllTask);
        }
        [HttpPost]
        public IActionResult DeleteTask(string id)
        {
            _service.RemoveTask(id);
            return Json(id);
        }

        public IActionResult FinishTask()
        {

            return RedirectToAction("Index", "Home");
        }

    }
}

TodolistProject.Core/Views/Shared/MainNavLayoutPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using TodolistProject.Core.Models.UserModels;
@inject UserManager<CommonUser> UserManager
@inject SignInManager<CommonUser> SignInManager

@if (SignInManager.IsSignedIn(User))
{
    <ul class="nav nav-pills nav-fill">
        <li class="nav-item ">
            <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </li>

        <li class="nav-item ">
            <a asp-area="" asp-controller="Task" asp-action="CreateTask">Create new task</a>
        <li class="nav-item active">
            <a asp-area="" asp-controller="Task" asp-action="ShowAllTasks">Show all tasks</a>
        </li>

        @if (User.IsInRole("admin"))
        {
            <li class="nav-item ">
                <a asp-area="" asp-controller="Role" asp-action="ShowAllRoles">Admin control</a>
            </li>
        }

        <li class="pull-right nav navbar-nav">
            <form asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })" method="post" id="logoutForm">
                <button type="submit" class="btn btn-link navbar-btn" id="logout_button">Logout</button>
            </form>
        </li>
        <li class="pull-right nav navbar-nav">
            <a asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @UserManager.GetUserName(User)!</a>
        </li>
    </ul>
}
else
{

    <ul class="nav nav-pills nav-fill">
        <li class="nav-item">
            <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="pull-right">
            <a asp-area="Identity" asp-page="/Account/Register">Register</a>
        </li>
        <li class="pull-right">
            <a asp-area="Identity" asp-page="/Account/Login">Login</a>
        </li>
    </ul>

}

TodolistProject.Core/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />

    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/login_.css" />
    <link rel="stylesheet" href="~/css/RoleControl.css" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @RenderSection("scripts", required: false)
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <title>@ViewData["Title"] - To do list</title>
</head>
<body>
    <header>
        <nav>
            <partial name="MainNavLayoutPartial" />
            <hr />
        </nav>
    </header>

    <main>
        <article class="col-md-10 col-md-offset-1">
            @RenderBody()
        </article>
    </main>

    <footer class="col-md-10 col-md-offset-1">
        <hr />
        <div class="kek">

            <span>Copyright. TodolistProj. Kirill Lukyanenko Just trying Bootstrap #goodluck #lol</span>

        </div>
    </footer>
   </body>
</html>
    